version: '3'
services:
  angular-app:
    build:
      context: ./profile-management-app
      dockerfile: Dockerfile
    ports:
      - "80:80"
  spring-boot-app:
    build:
      context: ./spring_boot_backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/profile_management?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 
